name: CI · Build & Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set lowercase variables
        id: vars
        run: |
          REPO_OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="my-flask-app"
          echo "repo_owner_lc=$REPO_OWNER_LC" >> $GITHUB_OUTPUT
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build \
            --file Dockerfile \
            --tag ghcr.io/${{ steps.vars.outputs.repo_owner_lc }}/${{ steps.vars.outputs.image_name }}:${{ github.sha }} \
            .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ steps.vars.outputs.repo_owner_lc }}/${{ steps.vars.outputs.image_name }}:${{ github.sha }}

      - name: Save Docker image to tarball
        run: |
          docker save ghcr.io/${{ steps.vars.outputs.repo_owner_lc }}/${{ steps.vars.outputs.image_name }}:${{ github.sha }} -o image.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-tar
          path: image.tar
